### ISSUE TITLE
`SignedInteger & UnsignedInteger` is probably the wrong bounds

### ISSUE THREAD

**Issue by Dante-Broggi** [mattt/Euler#16]
What I assume was meant was one of (the non-existent) `P | Q`, duplicating the functions for `SignedInteger` and `UnsignedInteger` separately, or use `BinaryInteger`.

This is because no type does, should, or is semantically permitted to conform to both `SignedInteger & UnsignedInteger`.

**Comment by mattt** [comment]
Indeed you're correct, @Dante-Broggi. What I intended to do was redeclare the functions for both types. This is now fixed in 64cebc3. Thanks!
